using RGB.NET.Core;
using System.Collections.Generic;

namespace Artemis.Plugins.Wrappers.Logitech.Services
{
    internal static class LedMapping
    {
        internal static readonly Dictionary<LogitechLedId, LedId> LogitechLedIds = new()
        {
            { LogitechLedId.ESC, LedId.Keyboard_Escape },
            { LogitechLedId.F1, LedId.Keyboard_F1 },
            { LogitechLedId.F2, LedId.Keyboard_F2 },
            { LogitechLedId.F3, LedId.Keyboard_F3 },
            { LogitechLedId.F4, LedId.Keyboard_F4 },
            { LogitechLedId.F5, LedId.Keyboard_F5 },
            { LogitechLedId.F6, LedId.Keyboard_F6 },
            { LogitechLedId.F7, LedId.Keyboard_F7 },
            { LogitechLedId.F8, LedId.Keyboard_F8 },
            { LogitechLedId.F9, LedId.Keyboard_F9 },
            { LogitechLedId.F10, LedId.Keyboard_F10 },
            { LogitechLedId.F11, LedId.Keyboard_F11 },
            { LogitechLedId.TILDE, LedId.Keyboard_GraveAccentAndTilde },
            { LogitechLedId.ONE, LedId.Keyboard_1 },
            { LogitechLedId.TWO, LedId.Keyboard_2 },
            { LogitechLedId.THREE, LedId.Keyboard_3 },
            { LogitechLedId.FOUR, LedId.Keyboard_4 },
            { LogitechLedId.FIVE, LedId.Keyboard_5 },
            { LogitechLedId.SIX, LedId.Keyboard_6 },
            { LogitechLedId.SEVEN, LedId.Keyboard_7 },
            { LogitechLedId.EIGHT, LedId.Keyboard_8 },
            { LogitechLedId.NINE, LedId.Keyboard_9 },
            { LogitechLedId.ZERO, LedId.Keyboard_0 },
            { LogitechLedId.MINUS, LedId.Keyboard_MinusAndUnderscore },
            { LogitechLedId.TAB, LedId.Keyboard_Tab },
            { LogitechLedId.Q, LedId.Keyboard_Q },
            { LogitechLedId.W, LedId.Keyboard_W },
            { LogitechLedId.E, LedId.Keyboard_E },
            { LogitechLedId.R, LedId.Keyboard_R },
            { LogitechLedId.T, LedId.Keyboard_T },
            { LogitechLedId.Y, LedId.Keyboard_Y },
            { LogitechLedId.U, LedId.Keyboard_U },
            { LogitechLedId.I, LedId.Keyboard_I },
            { LogitechLedId.O, LedId.Keyboard_O },
            { LogitechLedId.P, LedId.Keyboard_P },
            { LogitechLedId.OPEN_BRACKET, LedId.Keyboard_BracketLeft },
            { LogitechLedId.CAPS_LOCK, LedId.Keyboard_CapsLock },
            { LogitechLedId.A, LedId.Keyboard_A },
            { LogitechLedId.S, LedId.Keyboard_S },
            { LogitechLedId.D, LedId.Keyboard_D },
            { LogitechLedId.F, LedId.Keyboard_F },
            { LogitechLedId.G, LedId.Keyboard_G },
            { LogitechLedId.H, LedId.Keyboard_H },
            { LogitechLedId.J, LedId.Keyboard_J },
            { LogitechLedId.K, LedId.Keyboard_K },
            { LogitechLedId.L, LedId.Keyboard_L },
            { LogitechLedId.SEMICOLON, LedId.Keyboard_SemicolonAndColon },
            { LogitechLedId.APOSTROPHE, LedId.Keyboard_ApostropheAndDoubleQuote },
            { LogitechLedId.LEFT_SHIFT, LedId.Keyboard_LeftShift },
            { LogitechLedId.Z, LedId.Keyboard_Z },
            { LogitechLedId.X, LedId.Keyboard_X },
            { LogitechLedId.C, LedId.Keyboard_C },
            { LogitechLedId.V, LedId.Keyboard_V },
            { LogitechLedId.B, LedId.Keyboard_B },
            { LogitechLedId.N, LedId.Keyboard_N },
            { LogitechLedId.M, LedId.Keyboard_M },
            { LogitechLedId.COMMA, LedId.Keyboard_CommaAndLessThan },
            { LogitechLedId.PERIOD, LedId.Keyboard_PeriodAndBiggerThan },
            { LogitechLedId.FORWARD_SLASH, LedId.Keyboard_SlashAndQuestionMark },
            { LogitechLedId.LEFT_CONTROL, LedId.Keyboard_LeftCtrl },
            { LogitechLedId.LEFT_WINDOWS, LedId.Keyboard_LeftGui },
            { LogitechLedId.LEFT_ALT, LedId.Keyboard_LeftAlt },
            { LogitechLedId.SPACE, LedId.Keyboard_Space },
            { LogitechLedId.RIGHT_ALT, LedId.Keyboard_RightAlt },
            { LogitechLedId.RIGHT_WINDOWS, LedId.Keyboard_RightGui },
            { LogitechLedId.APPLICATION_SELECT, LedId.Keyboard_Application },
            { LogitechLedId.F12, LedId.Keyboard_F12 },
            { LogitechLedId.PRINT_SCREEN, LedId.Keyboard_PrintScreen },
            { LogitechLedId.SCROLL_LOCK, LedId.Keyboard_ScrollLock },
            { LogitechLedId.PAUSE_BREAK, LedId.Keyboard_PauseBreak },
            { LogitechLedId.INSERT, LedId.Keyboard_Insert },
            { LogitechLedId.HOME, LedId.Keyboard_Home },
            { LogitechLedId.PAGE_UP, LedId.Keyboard_PageUp },
            { LogitechLedId.CLOSE_BRACKET, LedId.Keyboard_BracketRight },
            { LogitechLedId.BACKSLASH, LedId.Keyboard_NonUsBackslash },
            //{ LogitechLedId.TILDE, LedId.Keyboard_NonUsTilde },
            { LogitechLedId.ENTER, LedId.Keyboard_Enter },
            { LogitechLedId.EQUALS, LedId.Keyboard_EqualsAndPlus },
            { LogitechLedId.BACKSPACE, LedId.Keyboard_Backspace },
            { LogitechLedId.KEYBOARD_DELETE, LedId.Keyboard_Delete },
            { LogitechLedId.END, LedId.Keyboard_End },
            { LogitechLedId.PAGE_DOWN, LedId.Keyboard_PageDown },
            { LogitechLedId.RIGHT_SHIFT, LedId.Keyboard_RightShift },
            { LogitechLedId.RIGHT_CONTROL, LedId.Keyboard_RightCtrl },
            { LogitechLedId.ARROW_UP, LedId.Keyboard_ArrowUp },
            { LogitechLedId.ARROW_LEFT, LedId.Keyboard_ArrowLeft },
            { LogitechLedId.ARROW_DOWN, LedId.Keyboard_ArrowDown },
            { LogitechLedId.ARROW_RIGHT, LedId.Keyboard_ArrowRight },
            { LogitechLedId.NUM_LOCK, LedId.Keyboard_NumLock },
            { LogitechLedId.NUM_SLASH, LedId.Keyboard_NumSlash },
            { LogitechLedId.NUM_ASTERISK, LedId.Keyboard_NumAsterisk },
            { LogitechLedId.NUM_MINUS, LedId.Keyboard_NumMinus },
            { LogitechLedId.NUM_PLUS, LedId.Keyboard_NumPlus },
            { LogitechLedId.NUM_ENTER, LedId.Keyboard_NumEnter },
            { LogitechLedId.NUM_SEVEN, LedId.Keyboard_Num7 },
            { LogitechLedId.NUM_EIGHT, LedId.Keyboard_Num8 },
            { LogitechLedId.NUM_NINE, LedId.Keyboard_Num9 },
            { LogitechLedId.NUM_FOUR, LedId.Keyboard_Num4 },
            { LogitechLedId.NUM_FIVE, LedId.Keyboard_Num5 },
            { LogitechLedId.NUM_SIX, LedId.Keyboard_Num6 },
            { LogitechLedId.NUM_ONE, LedId.Keyboard_Num1 },
            { LogitechLedId.NUM_TWO, LedId.Keyboard_Num2 },
            { LogitechLedId.NUM_THREE, LedId.Keyboard_Num3 },
            { LogitechLedId.NUM_ZERO, LedId.Keyboard_Num0 },
            { LogitechLedId.NUM_PERIOD, LedId.Keyboard_NumPeriodAndDelete },
            { LogitechLedId.G_1, LedId.Keyboard_Programmable1 },
            { LogitechLedId.G_2, LedId.Keyboard_Programmable2 },
            { LogitechLedId.G_3, LedId.Keyboard_Programmable3 },
            { LogitechLedId.G_4, LedId.Keyboard_Programmable4 },
            { LogitechLedId.G_5, LedId.Keyboard_Programmable5 },
            { LogitechLedId.G_6, LedId.Keyboard_Programmable6 },
            { LogitechLedId.G_7, LedId.Keyboard_Programmable7 },
            { LogitechLedId.G_8, LedId.Keyboard_Programmable8 },
            { LogitechLedId.G_9, LedId.Keyboard_Programmable9 },
            { LogitechLedId.G_LOGO, LedId.Logo },
            { LogitechLedId.G_BADGE, LedId.Keyboard_Custom1 },
        };

        internal static readonly Dictionary<DirectInputScanCode, LedId> DirectInputScanCodes = new()
        {
            [DirectInputScanCode.DIK_ESCAPE] = LedId.Keyboard_Escape,
            [DirectInputScanCode.DIK_1] = LedId.Keyboard_1,
            [DirectInputScanCode.DIK_2] = LedId.Keyboard_2,
            [DirectInputScanCode.DIK_3] = LedId.Keyboard_3,
            [DirectInputScanCode.DIK_4] = LedId.Keyboard_4,
            [DirectInputScanCode.DIK_5] = LedId.Keyboard_5,
            [DirectInputScanCode.DIK_6] = LedId.Keyboard_6,
            [DirectInputScanCode.DIK_7] = LedId.Keyboard_7,
            [DirectInputScanCode.DIK_8] = LedId.Keyboard_8,
            [DirectInputScanCode.DIK_9] = LedId.Keyboard_9,
            [DirectInputScanCode.DIK_0] = LedId.Keyboard_0,
            [DirectInputScanCode.DIK_MINUS] = LedId.Keyboard_MinusAndUnderscore,
            [DirectInputScanCode.DIK_EQUALS] = LedId.Keyboard_EqualsAndPlus,
            [DirectInputScanCode.DIK_BACK] = LedId.Keyboard_Backspace,
            [DirectInputScanCode.DIK_TAB] = LedId.Keyboard_Tab,
            [DirectInputScanCode.DIK_Q] = LedId.Keyboard_Q,
            [DirectInputScanCode.DIK_W] = LedId.Keyboard_W,
            [DirectInputScanCode.DIK_E] = LedId.Keyboard_E,
            [DirectInputScanCode.DIK_R] = LedId.Keyboard_R,
            [DirectInputScanCode.DIK_T] = LedId.Keyboard_T,
            [DirectInputScanCode.DIK_Y] = LedId.Keyboard_Y,
            [DirectInputScanCode.DIK_U] = LedId.Keyboard_U,
            [DirectInputScanCode.DIK_I] = LedId.Keyboard_I,
            [DirectInputScanCode.DIK_O] = LedId.Keyboard_O,
            [DirectInputScanCode.DIK_P] = LedId.Keyboard_P,
            [DirectInputScanCode.DIK_LBRACKET] = LedId.Keyboard_BracketLeft,
            [DirectInputScanCode.DIK_RBRACKET] = LedId.Keyboard_BracketRight,
            [DirectInputScanCode.DIK_RETURN] = LedId.Keyboard_Enter,
            [DirectInputScanCode.DIK_LContol] = LedId.Keyboard_LeftCtrl,
            [DirectInputScanCode.DIK_A] = LedId.Keyboard_A,
            [DirectInputScanCode.DIK_S] = LedId.Keyboard_S,
            [DirectInputScanCode.DIK_D] = LedId.Keyboard_D,
            [DirectInputScanCode.DIK_F] = LedId.Keyboard_F,
            [DirectInputScanCode.DIK_G] = LedId.Keyboard_G,
            [DirectInputScanCode.DIK_H] = LedId.Keyboard_H,
            [DirectInputScanCode.DIK_J] = LedId.Keyboard_J,
            [DirectInputScanCode.DIK_K] = LedId.Keyboard_K,
            [DirectInputScanCode.DIK_L] = LedId.Keyboard_L,
            [DirectInputScanCode.DIK_SEMICOLON] = LedId.Keyboard_SemicolonAndColon,
            [DirectInputScanCode.DIK_APOSTROPHE] = LedId.Keyboard_ApostropheAndDoubleQuote,
            [DirectInputScanCode.DIK_GRAVE] = LedId.Keyboard_GraveAccentAndTilde,
            [DirectInputScanCode.DIK_LSHIFT] = LedId.Keyboard_LeftShift,
            [DirectInputScanCode.DIK_BACKSLASH] = LedId.Keyboard_Backslash,
            [DirectInputScanCode.DIK_Z] = LedId.Keyboard_Z,
            [DirectInputScanCode.DIK_X] = LedId.Keyboard_X,
            [DirectInputScanCode.DIK_C] = LedId.Keyboard_C,
            [DirectInputScanCode.DIK_V] = LedId.Keyboard_V,
            [DirectInputScanCode.DIK_B] = LedId.Keyboard_B,
            [DirectInputScanCode.DIK_N] = LedId.Keyboard_N,
            [DirectInputScanCode.DIK_M] = LedId.Keyboard_M,
            [DirectInputScanCode.DIK_COMMA] = LedId.Keyboard_CommaAndLessThan,
            [DirectInputScanCode.DIK_PERIOD] = LedId.Keyboard_PeriodAndBiggerThan,
            [DirectInputScanCode.DIK_SLASH] = LedId.Keyboard_SlashAndQuestionMark,
            [DirectInputScanCode.DIK_RSHIFT] = LedId.Keyboard_RightShift,
            [DirectInputScanCode.DIK_MULTIPLY] = LedId.Keyboard_NumAsterisk,
            [DirectInputScanCode.DIK_LMENU] = LedId.Keyboard_LeftAlt,
            [DirectInputScanCode.DIK_SPACE] = LedId.Keyboard_Space,
            [DirectInputScanCode.DIK_CAPITAL] = LedId.Keyboard_CapsLock,
            [DirectInputScanCode.DIK_F1] = LedId.Keyboard_F1,
            [DirectInputScanCode.DIK_F2] = LedId.Keyboard_F2,
            [DirectInputScanCode.DIK_F3] = LedId.Keyboard_F3,
            [DirectInputScanCode.DIK_F4] = LedId.Keyboard_F4,
            [DirectInputScanCode.DIK_F5] = LedId.Keyboard_F5,
            [DirectInputScanCode.DIK_F6] = LedId.Keyboard_F6,
            [DirectInputScanCode.DIK_F7] = LedId.Keyboard_F7,
            [DirectInputScanCode.DIK_F8] = LedId.Keyboard_F8,
            [DirectInputScanCode.DIK_F9] = LedId.Keyboard_F9,
            [DirectInputScanCode.DIK_F10] = LedId.Keyboard_F10,
            [DirectInputScanCode.DIK_NUMLOCK] = LedId.Keyboard_NumLock,
            [DirectInputScanCode.DIK_SCROLL] = LedId.Keyboard_ScrollLock,
            [DirectInputScanCode.DIK_NUMPAD7] = LedId.Keyboard_Num7,
            [DirectInputScanCode.DIK_NUMPAD8] = LedId.Keyboard_Num8,
            [DirectInputScanCode.DIK_NUMPAD9] = LedId.Keyboard_Num9,
            [DirectInputScanCode.DIK_SUBTRACT] = LedId.Keyboard_NumMinus,
            [DirectInputScanCode.DIK_NUMPAD4] = LedId.Keyboard_Num4,
            [DirectInputScanCode.DIK_NUMPAD5] = LedId.Keyboard_Num5,
            [DirectInputScanCode.DIK_NUMPAD6] = LedId.Keyboard_Num6,
            [DirectInputScanCode.DIK_ADD] = LedId.Keyboard_NumPlus,
            [DirectInputScanCode.DIK_NUMPAD1] = LedId.Keyboard_Num1,
            [DirectInputScanCode.DIK_NUMPAD2] = LedId.Keyboard_Num2,
            [DirectInputScanCode.DIK_NUMPAD3] = LedId.Keyboard_Num3,
            [DirectInputScanCode.DIK_NUMPAD0] = LedId.Keyboard_Num0,
            [DirectInputScanCode.DIK_DECIMAL] = LedId.Keyboard_NumPeriodAndDelete,
            [DirectInputScanCode.DIK_F11] = LedId.Keyboard_F11,
            [DirectInputScanCode.DIK_F12] = LedId.Keyboard_F12,
            //[DirectInputScanCode.DIK_F13] = LedId.Keyboard_F13,
            //[DirectInputScanCode.DIK_F14] = LedId.Keyboard_F14,
            //[DirectInputScanCode.DIK_F15] = LedId.Keyboard_F15,
            //[DirectInputScanCode.DIK_KANA] = LedId.Keyboard_KANA,
            //[DirectInputScanCode.DIK_CONVERT] = LedId.Keyboard_CONVERT,
            //[DirectInputScanCode.DIK_NOCONVERT] = LedId.Keyboard_NOCONVERT,
            //[DirectInputScanCode.DIK_YEN] = LedId.Keyboard_YEN,
            //[DirectInputScanCode.DIK_NUMPADEQUALS] = LedId.Keyboard_NUMPADEQUALS,
            //[DirectInputScanCode.DIK_CIRCUMFLEX] = LedId.Keyboard_CIRCUMFLEX,
            //[DirectInputScanCode.DIK_AT] = LedId.Keyboard_AT,
            //[DirectInputScanCode.DIK_COLON] = LedId.Keyboard_COLON,
            //[DirectInputScanCode.DIK_UNDERLINE] = LedId.Keyboard_UNDERLINE,
            //[DirectInputScanCode.DIK_KANJI] = LedId.Keyboard_KANJI,
            //[DirectInputScanCode.DIK_STOP] = LedId.Keyboard_STOP,
            //[DirectInputScanCode.DIK_AX] = LedId.Keyboard_AX,
            //[DirectInputScanCode.DIK_UNLABELED] = LedId.Keyboard_UNLABELED,
            [DirectInputScanCode.DIK_NUMPADENTER] = LedId.Keyboard_NumEnter,
            [DirectInputScanCode.DIK_RCONTROL] = LedId.Keyboard_RightCtrl,
            //[DirectInputScanCode.DIK_NUMPADCOMMA] = LedId.Keyboard_NUMPADCOMMA,
            [DirectInputScanCode.DIK_DIVIDE] = LedId.Keyboard_NumSlash,
            //[DirectInputScanCode.DIK_SYSRQ] = LedId.Keyboard_SYSs,//TODO
            [DirectInputScanCode.DIK_RMENU] = LedId.Keyboard_RightAlt,
            [DirectInputScanCode.DIK_PAUSE] = LedId.Keyboard_PauseBreak,
            [DirectInputScanCode.DIK_HOME] = LedId.Keyboard_Home,
            [DirectInputScanCode.DIK_UP] = LedId.Keyboard_ArrowUp,
            [DirectInputScanCode.DIK_PRIOR] = LedId.Keyboard_PageUp,
            [DirectInputScanCode.DIK_LEFT] = LedId.Keyboard_ArrowLeft,
            [DirectInputScanCode.DIK_RIGHT] = LedId.Keyboard_ArrowRight,
            [DirectInputScanCode.DIK_END] = LedId.Keyboard_End,
            [DirectInputScanCode.DIK_DOWN] = LedId.Keyboard_ArrowDown,
            [DirectInputScanCode.DIK_NEXT] = LedId.Keyboard_PageDown,
            [DirectInputScanCode.DIK_INSERT] = LedId.Keyboard_Insert,
            [DirectInputScanCode.DIK_DELETE] = LedId.Keyboard_Delete,
            [DirectInputScanCode.DIK_LWIN] = LedId.Keyboard_LeftGui,
            [DirectInputScanCode.DIK_RWIN] = LedId.Keyboard_RightGui,
            [DirectInputScanCode.DIK_APPS] = LedId.Keyboard_Application,
            //[DirectInputScanCode.DIK_POWER] = LedId.Keyboard_POWER,
            //[DirectInputScanCode.DIK_SLEEP] = LedId.Keyboard_SLEEP
        };

        internal static readonly Dictionary<int, LedId> BitmapMap = new()
        {
            [0] = LedId.Keyboard_Escape,
            [4] = LedId.Keyboard_F1,
            [8] = LedId.Keyboard_F2,
            [12] = LedId.Keyboard_F3,
            [16] = LedId.Keyboard_F4,
            [20] = LedId.Keyboard_F5,
            [24] = LedId.Keyboard_F6,
            [28] = LedId.Keyboard_F7,
            [32] = LedId.Keyboard_F8,
            [36] = LedId.Keyboard_F9,
            [40] = LedId.Keyboard_F10,
            [44] = LedId.Keyboard_F11,
            [48] = LedId.Keyboard_F12,
            [52] = LedId.Keyboard_PrintScreen,
            [56] = LedId.Keyboard_ScrollLock,
            [60] = LedId.Keyboard_PauseBreak,
            [84] = LedId.Keyboard_GraveAccentAndTilde,
            [88] = LedId.Keyboard_1,
            [92] = LedId.Keyboard_2,
            [96] = LedId.Keyboard_3,
            [100] = LedId.Keyboard_4,
            [104] = LedId.Keyboard_5,
            [108] = LedId.Keyboard_6,
            [112] = LedId.Keyboard_7,
            [116] = LedId.Keyboard_8,
            [120] = LedId.Keyboard_9,
            [124] = LedId.Keyboard_0,
            [128] = LedId.Keyboard_MinusAndUnderscore,
            [132] = LedId.Keyboard_EqualsAndPlus,
            [136] = LedId.Keyboard_Backspace,
            [140] = LedId.Keyboard_Insert,
            [144] = LedId.Keyboard_Home,
            [148] = LedId.Keyboard_PageUp,
            [152] = LedId.Keyboard_NumLock,
            [156] = LedId.Keyboard_NumSlash,
            [160] = LedId.Keyboard_NumAsterisk,
            [164] = LedId.Keyboard_NumMinus,
            [168] = LedId.Keyboard_Tab,
            [172] = LedId.Keyboard_Q,
            [176] = LedId.Keyboard_W,
            [180] = LedId.Keyboard_E,
            [184] = LedId.Keyboard_R,
            [188] = LedId.Keyboard_T,
            [192] = LedId.Keyboard_Y,
            [196] = LedId.Keyboard_U,
            [200] = LedId.Keyboard_I,
            [204] = LedId.Keyboard_O,
            [208] = LedId.Keyboard_P,
            [212] = LedId.Keyboard_BracketLeft,
            [216] = LedId.Keyboard_BracketRight,
            [220] = LedId.Keyboard_NonUsBackslash,
            [224] = LedId.Keyboard_Delete,
            [228] = LedId.Keyboard_End,
            [232] = LedId.Keyboard_PageDown,
            [236] = LedId.Keyboard_Num7,
            [240] = LedId.Keyboard_Num8,
            [244] = LedId.Keyboard_Num9,
            [248] = LedId.Keyboard_NumPlus,
            [252] = LedId.Keyboard_CapsLock,
            [256] = LedId.Keyboard_A,
            [260] = LedId.Keyboard_S,
            [264] = LedId.Keyboard_D,
            [268] = LedId.Keyboard_F,
            [272] = LedId.Keyboard_G,
            [276] = LedId.Keyboard_H,
            [280] = LedId.Keyboard_J,
            [284] = LedId.Keyboard_K,
            [288] = LedId.Keyboard_L,
            [292] = LedId.Keyboard_SemicolonAndColon,
            [296] = LedId.Keyboard_ApostropheAndDoubleQuote,
            [304] = LedId.Keyboard_Enter,
            [320] = LedId.Keyboard_Num4,
            [324] = LedId.Keyboard_Num5,
            [328] = LedId.Keyboard_Num6,
            [336] = LedId.Keyboard_LeftShift,
            [344] = LedId.Keyboard_Z,
            [348] = LedId.Keyboard_X,
            [352] = LedId.Keyboard_C,
            [356] = LedId.Keyboard_V,
            [360] = LedId.Keyboard_B,
            [364] = LedId.Keyboard_N,
            [368] = LedId.Keyboard_M,
            [372] = LedId.Keyboard_CommaAndLessThan,
            [376] = LedId.Keyboard_PeriodAndBiggerThan,
            [380] = LedId.Keyboard_SlashAndQuestionMark,
            [388] = LedId.Keyboard_RightShift,
            [396] = LedId.Keyboard_ArrowUp,
            [404] = LedId.Keyboard_Num1,
            [408] = LedId.Keyboard_Num2,
            [412] = LedId.Keyboard_Num3,
            [416] = LedId.Keyboard_NumEnter,
            [420] = LedId.Keyboard_LeftCtrl,
            [424] = LedId.Keyboard_LeftGui,
            [428] = LedId.Keyboard_LeftAlt,
            [440] = LedId.Keyboard_Space,
            [464] = LedId.Keyboard_RightAlt,
            [468] = LedId.Keyboard_RightGui,
            [472] = LedId.Keyboard_Application,
            [476] = LedId.Keyboard_RightCtrl,
            [480] = LedId.Keyboard_ArrowLeft,
            [484] = LedId.Keyboard_ArrowDown,
            [488] = LedId.Keyboard_ArrowRight,
            [492] = LedId.Keyboard_Num0,
            [496] = LedId.Keyboard_NumPeriodAndDelete,
        };

        internal static readonly Dictionary<HidCode, LedId> HidCodes = new()
        {
            [HidCode.KEY_ESC] = LedId.Keyboard_Escape,
            [HidCode.KEY_F1] = LedId.Keyboard_F1,
            [HidCode.KEY_F2] = LedId.Keyboard_F2,
            [HidCode.KEY_F3] = LedId.Keyboard_F3,
            [HidCode.KEY_F4] = LedId.Keyboard_F4,
            [HidCode.KEY_F5] = LedId.Keyboard_F5,
            [HidCode.KEY_F6] = LedId.Keyboard_F6,
            [HidCode.KEY_F7] = LedId.Keyboard_F7,
            [HidCode.KEY_F8] = LedId.Keyboard_F8,
            [HidCode.KEY_F10] = LedId.Keyboard_F10,
            [HidCode.KEY_F11] = LedId.Keyboard_F11,
            [HidCode.KEY_F12] = LedId.Keyboard_F12,
            [HidCode.KEY_SYSRQ] = LedId.Keyboard_PrintScreen,
            [HidCode.KEY_SCROLLLOCK] = LedId.Keyboard_ScrollLock,
            [HidCode.KEY_PAUSE] = LedId.Keyboard_PauseBreak,
            [HidCode.KEY_GRAVE] = LedId.Keyboard_GraveAccentAndTilde,
            [HidCode.KEY_1] = LedId.Keyboard_1,
            [HidCode.KEY_2] = LedId.Keyboard_2,
            [HidCode.KEY_3] = LedId.Keyboard_3,
            [HidCode.KEY_4] = LedId.Keyboard_4,
            [HidCode.KEY_5] = LedId.Keyboard_5,
            [HidCode.KEY_6] = LedId.Keyboard_6,
            [HidCode.KEY_7] = LedId.Keyboard_7,
            [HidCode.KEY_8] = LedId.Keyboard_8,
            [HidCode.KEY_9] = LedId.Keyboard_9,
            [HidCode.KEY_0] = LedId.Keyboard_0,
            [HidCode.KEY_MINUS] = LedId.Keyboard_MinusAndUnderscore,
            [HidCode.KEY_EQUAL] = LedId.Keyboard_EqualsAndPlus,
            [HidCode.KEY_BACKSPACE] = LedId.Keyboard_Backspace,
            [HidCode.KEY_INSERT] = LedId.Keyboard_Insert,
            [HidCode.KEY_HOME] = LedId.Keyboard_Home,
            [HidCode.KEY_PAGEUP] = LedId.Keyboard_PageUp,
            [HidCode.KEY_NUMLOCK] = LedId.Keyboard_NumLock,
            [HidCode.KEY_KPSLASH] = LedId.Keyboard_NumSlash,
            [HidCode.KEY_KPASTERISK] = LedId.Keyboard_NumAsterisk,
            [HidCode.KEY_KPMINUS] = LedId.Keyboard_NumMinus,
            [HidCode.KEY_TAB] = LedId.Keyboard_Tab,
            [HidCode.KEY_Q] = LedId.Keyboard_Q,
            [HidCode.KEY_W] = LedId.Keyboard_W,
            [HidCode.KEY_E] = LedId.Keyboard_E,
            [HidCode.KEY_R] = LedId.Keyboard_R,
            [HidCode.KEY_T] = LedId.Keyboard_T,
            [HidCode.KEY_Y] = LedId.Keyboard_Y,
            [HidCode.KEY_U] = LedId.Keyboard_U,
            [HidCode.KEY_I] = LedId.Keyboard_I,
            [HidCode.KEY_O] = LedId.Keyboard_O,
            [HidCode.KEY_P] = LedId.Keyboard_P,
            [HidCode.KEY_LEFTBRACE] = LedId.Keyboard_BracketLeft,
            [HidCode.KEY_RIGHTBRACE] = LedId.Keyboard_BracketRight,
            [HidCode.KEY_BACKSLASH] = LedId.Keyboard_NonUsBackslash,
            [HidCode.KEY_DELETE] = LedId.Keyboard_Delete,
            [HidCode.KEY_END] = LedId.Keyboard_End,
            [HidCode.KEY_PAGEDOWN] = LedId.Keyboard_PageDown,
            [HidCode.KEY_KP7] = LedId.Keyboard_Num7,
            [HidCode.KEY_KP8] = LedId.Keyboard_Num8,
            [HidCode.KEY_KP9] = LedId.Keyboard_Num9,
            [HidCode.KEY_KPPLUS] = LedId.Keyboard_NumPlus,
            [HidCode.KEY_CAPSLOCK] = LedId.Keyboard_CapsLock,
            [HidCode.KEY_A] = LedId.Keyboard_A,
            [HidCode.KEY_S] = LedId.Keyboard_S,
            [HidCode.KEY_D] = LedId.Keyboard_D,
            [HidCode.KEY_F] = LedId.Keyboard_F,
            [HidCode.KEY_G] = LedId.Keyboard_G,
            [HidCode.KEY_H] = LedId.Keyboard_H,
            [HidCode.KEY_J] = LedId.Keyboard_J,
            [HidCode.KEY_K] = LedId.Keyboard_K,
            [HidCode.KEY_L] = LedId.Keyboard_L,
            [HidCode.KEY_SEMICOLON] = LedId.Keyboard_SemicolonAndColon,
            [HidCode.KEY_APOSTROPHE] = LedId.Keyboard_ApostropheAndDoubleQuote,
            [HidCode.KEY_ENTER] = LedId.Keyboard_Enter,
            [HidCode.KEY_KP4] = LedId.Keyboard_Num4,
            [HidCode.KEY_KP5] = LedId.Keyboard_Num5,
            [HidCode.KEY_KP6] = LedId.Keyboard_Num6,
            [HidCode.KEY_LEFTSHIFT] = LedId.Keyboard_LeftShift,
            [HidCode.KEY_Z] = LedId.Keyboard_Z,
            [HidCode.KEY_X] = LedId.Keyboard_X,
            [HidCode.KEY_C] = LedId.Keyboard_C,
            [HidCode.KEY_V] = LedId.Keyboard_V,
            [HidCode.KEY_B] = LedId.Keyboard_B,
            [HidCode.KEY_N] = LedId.Keyboard_N,
            [HidCode.KEY_M] = LedId.Keyboard_M,
            [HidCode.KEY_COMMA] = LedId.Keyboard_CommaAndLessThan,
            [HidCode.KEY_DOT] = LedId.Keyboard_PeriodAndBiggerThan,
            [HidCode.KEY_SLASH] = LedId.Keyboard_SlashAndQuestionMark,
            [HidCode.KEY_RIGHTSHIFT] = LedId.Keyboard_RightShift,
            [HidCode.KEY_UP] = LedId.Keyboard_ArrowUp,
            [HidCode.KEY_KP1] = LedId.Keyboard_Num1,
            [HidCode.KEY_KP2] = LedId.Keyboard_Num2,
            [HidCode.KEY_KP3] = LedId.Keyboard_Num3,
            [HidCode.KEY_KPENTER] = LedId.Keyboard_NumEnter,
            [HidCode.KEY_LEFTCTRL] = LedId.Keyboard_LeftCtrl,
            [HidCode.KEY_LEFTMETA] = LedId.Keyboard_LeftGui,
            [HidCode.KEY_LEFTALT] = LedId.Keyboard_LeftAlt,
            [HidCode.KEY_SPACE] = LedId.Keyboard_Space,
            [HidCode.KEY_RIGHTALT] = LedId.Keyboard_RightAlt,
            [HidCode.KEY_RIGHTMETA] = LedId.Keyboard_RightGui,
            [HidCode.KEY_RIGHTCTRL] = LedId.Keyboard_RightCtrl,
            [HidCode.KEY_LEFT] = LedId.Keyboard_ArrowLeft,
            [HidCode.KEY_DOWN] = LedId.Keyboard_ArrowDown,
            [HidCode.KEY_RIGHT] = LedId.Keyboard_ArrowRight,
            [HidCode.KEY_KPDOT] = LedId.Keyboard_Num0,
            [HidCode.KEY_KP0] = LedId.Keyboard_NumPeriodAndDelete,
        };

        //TODO:
        //QuartzCodes -> LedId

        internal static readonly Dictionary<LogitechLedId, int> ReversedBitmapMap = new()
        {
            [LogitechLedId.ESC] = 0,
            [LogitechLedId.F1] = 4,
            [LogitechLedId.F2] = 8,
            [LogitechLedId.F3] = 12,
            [LogitechLedId.F4] = 16,
            [LogitechLedId.F5] = 20,
            [LogitechLedId.F6] = 24,
            [LogitechLedId.F7] = 28,
            [LogitechLedId.F8] = 32,
            [LogitechLedId.F9] = 36,
            [LogitechLedId.F10] = 40,
            [LogitechLedId.F11] = 44,
            [LogitechLedId.F12] = 48,
            [LogitechLedId.PRINT_SCREEN] = 52,
            [LogitechLedId.SCROLL_LOCK] = 56,
            [LogitechLedId.PAUSE_BREAK] = 60,
            //64
            //68
            //72
            //76
            //80
            [LogitechLedId.TILDE] = 84,
            [LogitechLedId.ONE] = 88,
            [LogitechLedId.TWO] = 92,
            [LogitechLedId.THREE] = 96,
            [LogitechLedId.FOUR] = 100,
            [LogitechLedId.FIVE] = 104,
            [LogitechLedId.SIX] = 108,
            [LogitechLedId.SEVEN] = 112,
            [LogitechLedId.EIGHT] = 116,
            [LogitechLedId.NINE] = 120,
            [LogitechLedId.ZERO] = 124,
            [LogitechLedId.MINUS] = 128,
            [LogitechLedId.EQUALS] = 132,
            [LogitechLedId.BACKSPACE] = 136,
            [LogitechLedId.INSERT] = 140,
            [LogitechLedId.HOME] = 144,
            [LogitechLedId.PAGE_UP] = 148,
            [LogitechLedId.NUM_LOCK] = 152,
            [LogitechLedId.NUM_SLASH] = 156,
            [LogitechLedId.NUM_ASTERISK] = 160,
            [LogitechLedId.NUM_MINUS] = 164,
            [LogitechLedId.TAB] = 168,
            [LogitechLedId.Q] = 172,
            [LogitechLedId.W] = 176,
            [LogitechLedId.E] = 180,
            [LogitechLedId.R] = 184,
            [LogitechLedId.T] = 188,
            [LogitechLedId.Y] = 192,
            [LogitechLedId.U] = 196,
            [LogitechLedId.I] = 200,
            [LogitechLedId.O] = 204,
            [LogitechLedId.P] = 208,
            [LogitechLedId.OPEN_BRACKET] = 212,
            [LogitechLedId.CLOSE_BRACKET] = 216,
            [LogitechLedId.BACKSLASH] = 220,
            [LogitechLedId.KEYBOARD_DELETE] = 224,
            [LogitechLedId.END] = 228,
            [LogitechLedId.PAGE_DOWN] = 232,
            [LogitechLedId.NUM_SEVEN] = 236,
            [LogitechLedId.NUM_EIGHT] = 240,
            [LogitechLedId.NUM_NINE] = 244,
            [LogitechLedId.NUM_PLUS] = 248,
            [LogitechLedId.CAPS_LOCK] = 252,
            [LogitechLedId.A] = 256,
            [LogitechLedId.S] = 260,
            [LogitechLedId.D] = 264,
            [LogitechLedId.F] = 268,
            [LogitechLedId.G] = 272,
            [LogitechLedId.H] = 276,
            [LogitechLedId.J] = 280,
            [LogitechLedId.K] = 284,
            [LogitechLedId.L] = 288,
            [LogitechLedId.SEMICOLON] = 292,
            [LogitechLedId.APOSTROPHE] = 296,
            //[LogitechLedId.HASHTAG] = 300,
            [LogitechLedId.ENTER] = 304,
            //308
            //312
            //316
            [LogitechLedId.NUM_FOUR] = 320,
            [LogitechLedId.NUM_FIVE] = 324,
            [LogitechLedId.NUM_SIX] = 328,
            //332
            [LogitechLedId.LEFT_SHIFT] = 336,
            //[LogitechLedId.BACKSLASH_UK] = 340,
            [LogitechLedId.Z] = 344,
            [LogitechLedId.X] = 348,
            [LogitechLedId.C] = 352,
            [LogitechLedId.V] = 356,
            [LogitechLedId.B] = 360,
            [LogitechLedId.N] = 364,
            [LogitechLedId.M] = 368,
            [LogitechLedId.COMMA] = 372,
            [LogitechLedId.PERIOD] = 376,
            [LogitechLedId.FORWARD_SLASH] = 380,
            //[LogitechLedId.OEM102] = 384,
            [LogitechLedId.RIGHT_SHIFT] = 388,
            //392
            [LogitechLedId.ARROW_UP] = 396,
            //400
            [LogitechLedId.NUM_ONE] = 404,
            [LogitechLedId.NUM_TWO] = 408,
            [LogitechLedId.NUM_THREE] = 412,
            [LogitechLedId.NUM_ENTER] = 416,
            [LogitechLedId.LEFT_CONTROL] = 420,
            [LogitechLedId.LEFT_WINDOWS] = 424,
            [LogitechLedId.LEFT_ALT] = 428,
            //432
            //[LogitechLedId.JPN_MUHENKAN] = 436,
            [LogitechLedId.SPACE] = 440,
            //444
            //448
            //[LogitechLedId.JPN_HENKAN] = 452,
            //[LogitechLedId.JPN_HIRAGANA_KATAKANA] = 456,
            //460
            [LogitechLedId.RIGHT_ALT] = 464,
            [LogitechLedId.RIGHT_WINDOWS] = 468,
            [LogitechLedId.APPLICATION_SELECT] = 472,
            [LogitechLedId.RIGHT_CONTROL] = 476,
            [LogitechLedId.ARROW_LEFT] = 480,
            [LogitechLedId.ARROW_DOWN] = 484,
            [LogitechLedId.ARROW_RIGHT] = 488,
            [LogitechLedId.NUM_ZERO] = 492,
            [LogitechLedId.NUM_PERIOD] = 496,
            //500
        };

        internal static readonly Dictionary<HidCode, int> HidCodess = new()
        {
            [HidCode.KEY_ESC] = 0,
            [HidCode.KEY_F1] = 4,
            [HidCode.KEY_F2] = 8,
            [HidCode.KEY_F3] = 12,
            [HidCode.KEY_F4] = 16,
            [HidCode.KEY_F5] = 20,
            [HidCode.KEY_F6] = 24,
            [HidCode.KEY_F7] = 28,
            [HidCode.KEY_F8] = 32,
            [HidCode.KEY_F9] = 26,
            [HidCode.KEY_F10] = 40,
            [HidCode.KEY_F11] = 44,
            [HidCode.KEY_F12] = 48,
            [HidCode.KEY_SYSRQ] = 52,
            [HidCode.KEY_SCROLLLOCK] = 56,
            [HidCode.KEY_PAUSE] = 60,

            [HidCode.KEY_GRAVE] = 84,
            [HidCode.KEY_1] = 88,
            [HidCode.KEY_2] = 92,
            [HidCode.KEY_3] = 96,
            [HidCode.KEY_4] = 100,
            [HidCode.KEY_5] = 104,
            [HidCode.KEY_6] = 108,
            [HidCode.KEY_7] = 112,
            [HidCode.KEY_8] = 116,
            [HidCode.KEY_9] = 120,
            [HidCode.KEY_0] = 124,
            [HidCode.KEY_MINUS] = 128,
            [HidCode.KEY_EQUAL] = 132,
            [HidCode.KEY_BACKSPACE] = 136,
            [HidCode.KEY_INSERT] = 140,
            [HidCode.KEY_HOME] = 144,
            [HidCode.KEY_PAGEUP] = 148,
            [HidCode.KEY_NUMLOCK] = 152,
            [HidCode.KEY_KPSLASH] = 156,
            [HidCode.KEY_KPASTERISK] = 160,
            [HidCode.KEY_KPMINUS] = 164,

            [HidCode.KEY_TAB] = 168,
            [HidCode.KEY_Q] = 172,
            [HidCode.KEY_W] = 176,
            [HidCode.KEY_E] = 180,
            [HidCode.KEY_R] = 184,
            [HidCode.KEY_T] = 188,
            [HidCode.KEY_Y] = 192,
            [HidCode.KEY_U] = 196,
            [HidCode.KEY_I] = 200,
            [HidCode.KEY_O] = 204,
            [HidCode.KEY_P] = 208,
            [HidCode.KEY_LEFTBRACE] = 212,
            [HidCode.KEY_RIGHTBRACE] = 216,
            [HidCode.KEY_BACKSLASH] = 220,
            [HidCode.KEY_DELETE] = 224,
            [HidCode.KEY_END] = 228,
            [HidCode.KEY_PAGEDOWN] = 232,
            [HidCode.KEY_KP7] = 236,
            [HidCode.KEY_KP8] = 240,
            [HidCode.KEY_KP9] = 244,
            [HidCode.KEY_KPPLUS] = 248,

            [HidCode.KEY_CAPSLOCK] = 252,
            [HidCode.KEY_A] = 256,
            [HidCode.KEY_S] = 260,
            [HidCode.KEY_D] = 264,
            [HidCode.KEY_F] = 268,
            [HidCode.KEY_G] = 272,
            [HidCode.KEY_H] = 276,
            [HidCode.KEY_J] = 280,
            [HidCode.KEY_K] = 284,
            [HidCode.KEY_L] = 288,
            [HidCode.KEY_SEMICOLON] = 292,
            [HidCode.KEY_APOSTROPHE] = 296,
            [HidCode.KEY_HASHTILDE] = 300,
            [HidCode.KEY_ENTER] = 304,
            [HidCode.KEY_KP4] = 320,
            [HidCode.KEY_KP5] = 324,
            [HidCode.KEY_KP6] = 328,

            [HidCode.KEY_LEFTSHIFT] = 336,
            [HidCode.KEY_102ND] = 340,
            [HidCode.KEY_Z] = 344,
            [HidCode.KEY_X] = 348,
            [HidCode.KEY_C] = 352,
            [HidCode.KEY_V] = 356,
            [HidCode.KEY_B] = 360,
            [HidCode.KEY_N] = 364,
            [HidCode.KEY_M] = 368,
            [HidCode.KEY_COMMA] = 372,
            [HidCode.KEY_DOT] = 376,
            [HidCode.KEY_SLASH] = 380,
            //
            [HidCode.KEY_RIGHTSHIFT] = 388,
            //
            [HidCode.KEY_UP] = 396,
            [HidCode.KEY_KP1] = 404,
            [HidCode.KEY_KP2] = 408,
            [HidCode.KEY_KP3] = 412,
            [HidCode.KEY_KPENTER] = 416,

            [HidCode.KEY_LEFTCTRL] = 420,
            [HidCode.KEY_LEFTMETA] = 424,
            [HidCode.KEY_LEFTALT] = 428,
            [HidCode.KEY_SPACE] = 440,
            [HidCode.KEY_RIGHTALT] = 464,
            [HidCode.KEY_RIGHTMETA] = 468,
            [HidCode.KEY_RIGHTCTRL] = 476,
            [HidCode.KEY_LEFT] = 480,
            [HidCode.KEY_DOWN] = 484,
            [HidCode.KEY_RIGHT] = 488,
            [HidCode.KEY_KPDOT] = 492,
            [HidCode.KEY_KP0] = 496
        };
    }
}
